config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'
  post '/create' => "users#create"
  post '/process' => "sessions#login"
  
  get 'groups/main' => "users#main"

  post "/users/:id/groups/create" => "users#create_group"
  get 'groups/:group_id' => "users#show"

  post "groups/:group_id/join" => "users#join"
  post "groups/:group_id/leave" => "users#leave"
  delete "/groups/:group_id" => "users#destroy"

  get 'sessions/logout' => "sessions#logout"

  get 'users/show'

end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
  has_many :members, dependent: :destroy
  has_many :users_joined, through: :members, source: :user

  validates :name, presence: true, length: { :in => 5..50 }
  validates :desc, presence: true, length: { :in => 10..250 }
end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  has_many :members, dependent: :destroy
  has_many :groups, dependent: :destroy
  has_many :groups_joined, :through => :members, :source => :group 

  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
  validates :first_name, :last_name, presence: true, length: { :maximum => 50 }
  validates :email, presence: true, uniqueness: true, format: { with: EMAIL_REGEX }

  before_create do
    self.email = email.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user_id
    User.find(session[:user_id]).id if session[:user_id]
  end
  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
  helper_method :current_user_id
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def main
  end

  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
  end
  def login
    if User.find_by(email: params[:email]).try(:authenticate, params[:password])
      @user = User.find_by(email: params[:email])
      session[:user_id] = @user.id
      redirect_to "/groups/main"
    else 
      flash[:errors]="Invalid user email or password"
      redirect_to root_path
    end
  end
  def logout
    session[:id]= nil
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.create(user_params)
    if !@user.valid?
      flash[:errors] = @user.errors.full_messages
      redirect_to "/"
    else
      session[:user_id] = @user.id
      flash[:success]="Welcome!!!"
      redirect_to "/groups/main"
    end
  end

  def main
    @user = User.find(current_user)
    @groups = Group.all
  end
  def create_group
    @group = Group.new(name: params[:name], desc: params[:desc], user_id: session[:user_id])
    if !@group.valid?
      flash[:errors] = @group.errors.full_messages
      redirect_to "/groups/main"
    else
      @group.save
      flash[:success]="New group was created!!!"
      redirect_to "/groups/main"
    end
  end

  def show
    @group = Group.find(params[:group_id])
  end

  def join
    @user = User.find(current_user_id)
    @group = Group.find(params[:group_id])
    @member = Member.new(user: @user, group: @group)
    @member.save
    redirect_to "/groups/#{params[:group_id]}"
  end
   
  def leave
    @group = Group.find(params[:group_id])
    @member = Member.find_by(group: @group, user: current_user)
    @member.destroy
    redirect_to "/groups/#{params[:group_id]}"
  end 

  def destroy
    @group = Group.find(params[:group_id])
    @group.destroy
    redirect_to "/groups/main"
  end

  private
  def  user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/main.html.erb
<h1>Groups#main</h1>
<p>Find me in app/views/groups/main.html.erb</p>

app/views/groups/show.html.erb
<h1>Groups#show</h1>
<p>Find me in app/views/groups/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Organizations</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/create.html.erb
<%if flash[:errors]%>
    <%= flash[:errors] %>
<%end%>
<h2>Register</h2>
<form action="/create" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <table>
        <tr>
            <td><label for="first_name">First Name:</label></td>
            <td><input type="text" name="user[first_name]"></td>
        </tr>
        <tr>
            <td><label for="last_name">Last Name:</label></td>
            <td><input type="text" name="user[last_name]"></td>
        </tr>
        <tr>
            <td><label for="email">Email:</label></td>
            <td><input type="text" name="user[email]"></td>
        </tr>
        <tr>
            <td><label for="password">Password:</label></td>
            <td><input type="password" name="user[password]"></td>
        </tr>
        <tr>
            <td><label for="password_confirmation">Password Confirmation:</label></td>
            <td><input type="password" name="user[password_confirmation]"></td>
        </tr>
        <tr>
            <td><input type="submit" value="Register"></td>
    </table>
</form>
<h2>Login</h2>
<form action="/process" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <table>
        <tr>
            <td><label for="email">Email:</label></td>
            <td><input type="text" name="email"></td>
        </tr>
        <tr>
            <td><label for="password">Password:</label></td>
            <td><input type="password" name="password"></td>
        </tr>
        <tr>
            <td><input type="submit" value="Login"></td>
    </table>
</form>

app/views/users/main.html.erb
<a href= "/sessions/logout">Logout</a> <br>
<% if flash[:success] %>
    <p> <%= flash[:success] %> </p>
<% end %>
<%if flash[:errors]%>
    <%= flash[:errors] %>
<%end%>

<h1>Hi <%= @user.first_name %> <%= @user.last_name %> </h1>
<h3> Here are the organizations you may join:</h3>
<% @groups.each do |g| %>
    <h4><a href = "/groups/<%= g.id %>"> <%= g.name %></a></h4>
    
    <p> <%= g.desc %> </p>

    <% if current_user_id == g.user_id %>
        <td><form action="/groups/<%= g.id %>" method = "post">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"> 
            <input type="hidden" name="_method" value="delete">
            <input type="submit" value="delete group">
        </form></td> 
    <% end %>
<% end %>    

<div>
    <h4>Create a new organization:</h4>
    <form action = "/users/<%= current_user.id %>/groups/create" method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">    
        <p>Org Name: </p><input type="text" name="name">
        <p>Description: </p><input type="textarea" name="desc"><br>
        <br><input type="submit" value="Create">
    </form>
</div>

app/views/users/show.html.erb
<a href = "/groups/main">Dashboard </a> | <a href = "/sessions/logout"> Logout </a>
<h1> <%= @group.name %> </h1>
<h1> <%= @group.desc %> </h1>

<h3>Created by: <%= @group.user.first_name %> <%= @group.user.last_name%></h3>
<% if @group.users_joined_ids.include?(current_user.id) %>
    <form action="/groups/<%= @group.id %>/leave" method = "post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"> 
        <input type="submit" value="Leave Group">
    </form>
<% else %>
    <form action="/groups/<%= @group.id %>/join" method = "post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"> 
        <input type="submit" value="Join Group">
    </form>
<% end %>

<h3>Members:</h3>

<% @group.members.each do |member| %>
    <p> <%= member.user.first_name %> <%= member.user.last_name %></p>
<% end %>